name: my_porfolio
description: porfolio web app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  cupertino_icons: ^1.0.2
  get: ^4.5.1
  responsive_builder:
  url_launcher: ^6.0.2
  carousel_slider: ^4.2.1
  mailto: ^2.0.0
  email_validator: ^2.0.1
#  path_provider: ^2.1.5
#  image_picker: ^0.8.7+4
  flutter_email_sender: ^5.2.0
#  flutter_animation_progress_bar: ^2.3.1
#  pinch_zoom_release_unzoom:
#  flutter_launcher_icons: ^0.13.1
  simple_shadow: ^0.3.1
#  auto_size_text: ^3.0.0
#  scrollable_positioned_list: ^0.3.5
  animated_text_kit: ^4.2.2
  pie_chart: ^5.3.2
  flashy_tab_bar2: ^0.0.5
  flutter_native_splash: ^2.3.1
  web_smooth_scroll:
  firebase_core: ^3.12.1
  fluttertoast: ^8.2.12
  easy_pie_chart: ^1.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo/white_transparent_grey.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/black_transparent.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo/black_transparent.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo/black_transparent.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo/black_transparent.png"
    
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/projects/
    - assets/audios/

  fonts:
  
    - family: AlfaSlabOne
      fonts:
        - asset: assets/fonts/AlfaSlabOne-Regular.ttf

    - family: AmaticSC
      fonts:
        - asset: assets/fonts/AmaticSC-Regular.ttf
        - asset: assets/fonts/AmaticSC-Bold.ttf
          weight: 700
          
    - family: BalsamiqSans
      fonts:
        - asset: assets/fonts/BalsamiqSans-Regular.ttf
        - asset: assets/fonts/BalsamiqSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/BalsamiqSans-Italic.ttf
          style: italic
          
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
        - asset: assets/fonts/Caveat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Caveat-Medium.ttf
          weight: 300
        - asset: assets/fonts/Caveat-SemiBold.ttf
          weight: 600

    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 200
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
          
    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf
        
    - family: GloriaHallelujah
      fonts:
        - asset: assets/fonts/GloriaHallelujah-Regular.ttf

    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Light.ttf
          weight: 200
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 100

    - family: MeowScript
      fonts:
        - asset: assets/fonts/MeowScript-Regular.ttf

    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/MontserratAlternates-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
          weight: 700
        - asset: assets/fonts/MontserratAlternates-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratAlternates-Italic.ttf
          style: italic
        - asset: assets/fonts/MontserratAlternates-Light.ttf
          weight: 200
        - asset: assets/fonts/MontserratAlternates-Medium.ttf
          weight: 300
        - asset: assets/fonts/MontserratAlternates-ExtraLight.ttf
          weight: 100

    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Italic.ttf
          style: italic
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 200
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 300
        - asset: assets/fonts/Mulish-ExtraLight.ttf
          weight: 100

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 300

    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro-Regular.ttf
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/ReadexPro-Light.ttf
          weight: 200
        - asset: assets/fonts/ReadexPro-Medium.ttf
          weight: 300
        - asset: assets/fonts/ReadexPro-ExtraLight.ttf
          weight: 100

    - family: RedactedScript
      fonts:
        - asset: assets/fonts/RedactedScript-Regular.ttf
        - asset: assets/fonts/RedactedScript-Bold.ttf
          weight: 700
        - asset: assets/fonts/RedactedScript-Light.ttf
          weight: 200
          
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
        
    - family: Shalimar
      fonts:
        - asset: assets/fonts/Shalimar-Regular.ttf
